# Generated by Django 6.1 on 2026-08-31 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mass_kg', models.FloatField()),
                ('radius_km', models.FloatField()),
                ('diameter_km', models.FloatField()),
                ('gravity_m_s2', models.FloatField()),
                ('density_kg_m3', models.FloatField()),
                ('distance_from_sun_km', models.FloatField()),
                ('rotation_period_hours', models.FloatField()),
                ('orbital_period_days', models.FloatField()),
                ('axial_tilt_degrees', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Planet Mars',
            },
        ),
        migrations.CreateModel(
            name='LandingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('region', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('mars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landingsites', to='main.mars')),
            ],
        ),
        migrations.CreateModel(
            name='GeographicFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('feature_type', models.CharField(choices=[('mountain', 'Mountain'), ('volcano', 'Volcano'), ('canyon', 'Canyon'), ('crater', 'Crater'), ('valley', 'Valley'), ('plain', 'Plain')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation_m', models.FloatField(blank=True, null=True)),
                ('diameter_km', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('mars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographices', to='main.mars')),
            ],
        ),
        migrations.CreateModel(
            name='Atmosphere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_pressure_pa', models.FloatField()),
                ('average_temperature_c', models.FloatField()),
                ('composition', models.JSONField()),
                ('description', models.TextField()),
                ('mars', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atmosphere', to='main.mars')),
            ],
            options={
                'verbose_name_plural': 'Atmosphere',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('agency', models.CharField(max_length=100)),
                ('mission_type', models.CharField(choices=[('orbiter', 'Orbiter'), ('lander', 'Lander'), ('rover', 'Rover'), ('flyby', 'Flyby')], max_length=20)),
                ('launch_date', models.DateField()),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed'), ('inactive', 'Inactive')], max_length=20)),
                ('description', models.TextField()),
                ('mars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='main.mars')),
            ],
        ),
        migrations.CreateModel(
            name='Moon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('radius_km', models.FloatField()),
                ('mass_kg', models.FloatField()),
                ('orbital_period_days', models.FloatField()),
                ('description', models.TextField()),
                ('mars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moons', to='main.mars')),
            ],
        ),
        migrations.CreateModel(
            name='Rover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('landing_date', models.DateField()),
                ('landing_site', models.CharField(max_length=150)),
                ('current_status', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rover', to='main.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hemisphere', models.CharField(choices=[('northern', 'Northern Hemisphere'), ('southern', 'Southern Hemisphere')], max_length=10)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], max_length=10)),
                ('min_temperature_c', models.FloatField()),
                ('max_temperature_c', models.FloatField()),
                ('average_temperature_c', models.FloatField()),
                ('description', models.TextField()),
                ('mars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weathers', to='main.mars')),
            ],
            options={
                'verbose_name_plural': 'Weather',
                'constraints': [models.UniqueConstraint(fields=('hemisphere', 'season'), name='unique_hemisphere_season')],
            },
        ),
    ]
